theme: jekyll-theme-cayman
title: "NeoLAB Data Platform™"
layout: default
plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
